### ISSUE TITLE
NPE on map rendering. 

### ISSUE THREAD

**Issue by Maroon28** [BillyGalbreath/Pl3xMap#119]
Hi! I just installed the latest available build of Pl3xMap from actions, and upon rendering, my console gets spammed with this exact error. The error just keeps repeating for as long as a render is going. However, even after _pausing_ the render, the error continues to spam. Fully disabling the plugin is the only way to stop it. 

https://pastes.dev/4Y6oUAXDWn

**Comment by BillyGalbreath** [comment]
I fixed the NPE in the code to prevent the spam, but there is a bigger issue on your end where the light data isn't up to date, or is missing from your world. Since this looks to be from an earth world, you're going to have to run Chunky over it to force load all the chunks so they properly update to the currently running version.

**Comment by Maroon28** [comment]
I did run the server with --forceUpgrade, however that was on 1.19 and the render is running on 1.19.1. Does forceUpgrade not update light data or does a small patch version like that make a difference?
