### ISSUE TITLE
Map not fully rendered despite saying it is fully rendered

### ISSUE THREAD

**Issue by dino147** [BillyGalbreath/Pl3xMap#133]
I have an issue, I have given the command ./pl3xmap fullrender and the plugin says the map is fully rendered but it isn't:
![image](https://user-images.githubusercontent.com/19268931/206216014-13202715-f221-4f40-a7d3-c5df2ac20139.png)

**Comment by Roan-V** [comment]
In the future please put support questions in the discord


I am assuming your world has been generated by an older minecraft version

Pl3xmap can't work with these chunks in the older format, the chunks that have been loaded (aka, visited by players) will have been updated to the new format

To fix this you can let chunky force load all chunks and then when its done fullrender again.
Because the chunks are already generated, but just in an older version this will go pretty fast
