### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MuniuDev** [BillyGalbreath/Pl3xMap#183]
Hi,

I've been running Pl3xMap for a few years on my server and I really enjoy it!

Unfortunately, since 1.20.1 update I've been experiencing a constant memory leak that results in OoM termination of the server runtime. I've verified that removing Pl3xMap fixes the issue. I've also tested that using an external webserver (nginx) does not fix the issue.

Few parameters of my server:
```
MC version: 1.20.1
Paper version: 68
Pl3xMap version: 1.20.1-468 (with Pl3xMapClaims 1.20.1-30, I use GriefPrevention and WorldGuard)
4 CPUs, 8GB RAM (5GB allocated to server)

Plugins (besides Pl3xMap):
  AntiBookBan-1.3.jar
  AntiPopup-6.1.jar
  Chunky-1.3.92.jar
  CoreProtect-21.3.jar
  DoubleShulkerShells.jar
  DropHeads v3.7.13.jar
  EssentialsX-2.20.0.jar
  EssentialsXChat-2.20.0.jar
  EssentialsXSpawn-2.20.0.jar
  GriefPrevention 16.18.1.jar
  LuckPerms-Bukkit-5.4.40.jar
  Multiverse-Core-4.3.1.jar
  Multiverse-Inventories-4.2.2.jar
  Multiverse-Portals-4.2.1.jar
  OpenInv 4.3.1.jar
  ProtocolLib-5.0.0.jar
  QuickShop-5.1.2.2.jar
  SurvivalInvisiframes.jar
  TabList-bukkit-v5.7.3.jar
  Vault.jar
  WanderingTrades-1.8.1.jar
  gringotts-2.12.4.jar
  sleep-most-5.3.0.jar
  worldedit-bukkit-7.2.15.jar
  worldguard-bukkit-7.0.9-beta1.jar
```

I'm using Multiverse to hold a total of 5 dimensions (overworld, nether, end, overworld2, and creative realm (hidden from map))

Screenshot of memory usage at the server start:
![Screenshot_73](https://github.com/BillyGalbreath/Pl3xMap/assets/8275106/51683633-22b8-4ed4-85ac-fe7d2c34dbc0)

And then after 4h:
![Screenshot_74](https://github.com/BillyGalbreath/Pl3xMap/assets/8275106/b3080a6e-d6ee-424b-9195-a774c990820e)

And finally after about 7h:
![Screenshot_75](https://github.com/BillyGalbreath/Pl3xMap/assets/8275106/ff437c93-7eba-4ea7-9575-d2b3ed537dd8)

I'm attaching my config:
[config.zip](https://github.com/BillyGalbreath/Pl3xMap/files/12004540/config.zip)

Thank you for the work and the support with this issue.

**Comment by iTemmy** [comment]
I am getting this as well, adjusted server to have 20GB of memory and was running fine then would suddenly spike and use all 20GB after about 5-7 minutes.

Have attached heap dump from when server started and just before server crashed.

[server heap dumps.zip](https://github.com/BillyGalbreath/Pl3xMap/files/12063759/server.heap.dumps.zip)

**Comment by BillyGalbreath** [comment]
No, there is no memory leak.

Yes, Pl3xMap uses as much ram as it can. That's by design.

What you both are seeing is the server using more ram than the server has to give it. This is due to misconfigurations of the heap allocations on your part.

Let's take Temmy's example since it's got actual numbers I can point at. He has a server with 20GB of physical ram. He's telling the MC server it can use 18GB of that by setting 18432MB as his Xmx parameter in the startup script. This leaves little to no room for the OS to operate on or the JVM to breathe (the JVM comes with overhead).

Ok, so this is all fine and dandy, because he also told the JVM to start up with only 256MB of heap. this is will below the max limit, so it starts up and is fine. Until something starts needing more heap, then the JVM will grow that 256MB until it reaches the Xmx cap you set at 18GB. Except, the JVM's been crunching heavily on some numbers (in this case, Pl3xMap), so the JVM overhead is rather high. Very probably more than 2GB of overhead. And we still havent thought about the OS, or other programs running on the machine, etc etc. All of a sudden the server has run out of ram before it can even allocate all the heap space you told it it could have.

Boom. OOM.

You'll see the same OOM almost instantly if you were to follow Aikar's advice on his blog post about JVM flags where he states to make sure Xms _is the same value as_ Xmx. This is important, not only for his flags to operate properly, but to ensure the heap can and does get everything you tell it it can get.

Another thing you can do is lessen the burden on the JVM/heap by lowering the amount of threads Pl3xMap can use (its in the config.yml file). This will result in Pl3xMap needing less ram at one time to do what it needs to do. Since ya'll look to have only 4 cores, I recommend lowering the thread count to 1 for Pl3xMap.

And yet another thing you could do to lessen the burden on your heap is to turn on _both_ GC options in Pl3xMap's config file. This will make the GC run way more aggressively, cleaning out old, dead objects much faster that letting the JVM do it on it's own.

So yeah. TLDR; There's no memory leak. Do the 3 things I suggest and you should be fine.

**Comment by MuniuDev** [comment]
My server hosts only this single MC server for which I have 5GB (out of total 8GB, with 300MB used by linux)  assigned according to Aikar flags (Xmx == Xms). I've already been using both GC flags, and yesterday switched to 1 rendering thread (from -1). The exact same thing happened. In the past I've also experimented with 4GB assigned to the mc server but this didn't solve the issue.

To be perfectly clear, my server always takes up a constant amount of RAM unless I switch the Pl3xMap on, at that point, the RAM slowly crawls up and eventually causes server termination. To me this is a clear memory leak.

**Comment by matipoirierg** [comment]
Hi, I'm had this same issue, I'm running my server under a pterodactyl docker. The problem is that with pl3xmap the server starts increasing the overhead ignoring the xmx, I'm not a java developer so what I'm saying is probably wildly inaccurate but it's the only way I can explain this behavior from my knowledge. It all started with the 1.20 update. At the time I didn't know what it was so I just made a report on pterodactyl: https://github.com/pterodactyl/panel/issues/4816 hoping for a possible solution. Just yesterday I found out It was pl3xmap causing this, I had the problem on two different servers, I removed pl3xmap from those 2 and the overhead went to normal values again.
